name: macOS Brew Generate bump-formula-pr
on:
  push:
    branches: [brew-update-on-release]
  release:
    types: [published]
    branches: [main]

jobs:
  install_dependencies_and_build:
    name: Print the environment 
    runs-on: macos-latest
    steps:
      - name: Run everything
        env: 
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.githubAccess }}
          GITHUB_EMAIL: ${{ secrets.githubEmail }}      
        run: |
             git config --global user.email "${GITHUB_EMAIL}"
             git config --global user.name "${GITHUB_REPOSITORY_OWNER}"
             brew update
             brew upgrade
             URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/archive/${GITHUB_REF}.tar.gz"
             echo ${URL}
             curl "${URL}" -o download.tar.gz
             CHECKSUM=$(shasum -a256 download.tar.gz | cut -c1-64)
             brew bump-formula-pr --dry-run --no-browse --strict --online --url "${URL}" --sha256 "${CHECKSUM}"  timg
